# Build/check half of hyphence's go/ subtree. Outputs: the `hyphence` CLI
# binary (cmd/hyphence — the four format-only subcommands validate/meta/body/
# format over the RFC 0001 envelope), the `checks.go-test` hermetic
# `go test -tags test ./...` gate, and the Go devShell. The conformist
# format/lint lanes are wired in flake.nix (they need conformist.lib + `self`);
# the derived hooks/binaries are passed in here for the devShell only.
{
  nixpkgs,
  nixpkgs-master,
  # conformist (treefmt successor): the BARE binary on the devShell PATH
  # (the wrapper is the flake `formatter` output). Defaulted null so a
  # direct `import ./go/default.nix` without flake context still works.
  conformist ? null,
  # doppelgang provides `lint`, the flake.lock dedup gate. Defaulted null
  # so non-flake callers don't need it.
  doppelgang ? null,
  # The module-generated, toolchain-hermetic per-commit hook wrapper, on
  # the devShell PATH as `conformist-pre-commit` (the sweatfile
  # [hooks].pre-commit command). Defaulted null for non-flake callers.
  conformistPreCommit ? null,
  # Its merge-repair sibling (build.repair), on the devShell PATH as
  # `conformist-repair` — spinclass's merge-repair phase resolves it there,
  # so a cascade bump commit self-heals at merge time against the rebuilt
  # post-bump devshell (eng tier-B convergence; eng's fallback wrapper is
  # severed from child repos and would otherwise skip). Defaulted null for
  # non-flake callers.
  conformistRepair ? null,
  system,
  # Flake-input bridge table (see ./gomod.nix). Defaulted {} so non-flake
  # callers degrade to organic gomod2nix.toml resolution.
  goFlakeInputs ? { },
  version ? "dev",
  # docs/man.7 source dir (passed from flake.nix). When set, the CLI build
  # renders each *.md to a roff man page via pandoc in postInstall. Defaulted
  # null so non-flake callers skip the man-page step.
  man7Src ? null,
  # docs/man.1 source dir (passed from flake.nix), same pandoc-render
  # mechanism as man7Src but for the CLI reference page. Hand-written
  # rather than generated by futility.GenerateManpages (go/futility/
  # generate_manpages.go) — that codegen is pre-GA and not yet adopted
  # by this CLI's own wiring. Defaulted null so non-flake callers skip
  # the man-page step.
  man1Src ? null,
  # langlang's default package output (the CLI binary), passed from
  # flake.nix. Only used by grammar-vectors-test below; defaulted null
  # so non-flake callers skip that derivation entirely.
  langlang ? null,
  # docs/rfcs/hyphence-content.peg's Nix path (passed from flake.nix) —
  # outside go/'s own src fileset, so grammar-vectors-test needs it
  # threaded in explicitly. Defaulted null; required whenever langlang
  # is set (see grammar-vectors-test's assertion below).
  grammarPeg ? null,
}:
let
  # The fork's default.nix shim auto-applies overlays.default (the gomod2nix
  # overlay carrying goFlakeInputs support), so no explicit overlay here.
  pkgs = import nixpkgs { inherit system; };
  pkgs-master = import nixpkgs-master { inherit system; };

  # checks.go-test: the hermetic CI gate. CROWN JEWEL: the RFC conformance
  # suite (go/hyphence/rfc_conformance_test.go) is behind `//go:build test`,
  # so the `-tags test` flag is MANDATORY — without it the conformance
  # vectors silently don't run.
  #
  # hyphence is a binary-less library module, so the stock buildGoApplication
  # build/install (which expects a `main` to install) is replaced with a plain
  # `go build ./...` + the tagged test suite. configurePhase (gomod2nix dep
  # vendoring + the dewey bridge) is left intact, so module resolution is
  # unchanged.
  go-test = pkgs.buildGoApplication {
    pname = "hyphence-go-test";
    inherit version goFlakeInputs;
    src = ./.;
    pwd = ./.;
    modules = ./gomod2nix.toml;
    go = pkgs-master.go_1_26;
    GOTOOLCHAIN = "local";
    subPackages = [ "hyphence" ];

    buildPhase = ''
      runHook preBuild
      go build ./...
      runHook postBuild
    '';

    doCheck = true;
    checkPhase = ''
      runHook preCheck
      go test -tags test -p $NIX_BUILD_CORES ./...
      runHook postCheck
    '';

    installPhase = ''
      runHook preInstall
      mkdir -p "$out"
      runHook postInstall
    '';
  };

  # grammar-vectors-test: hyphence#9's langlang -input cross-check. Reuses
  # go-test's exact buildGoApplication shape but runs only TestGrammarVectors
  # (go/hyphence/grammar_vectors_test.go), with langlang on PATH and
  # HYPHENCE_GRAMMAR_PEG/LANGLANG_BIN set so the test's env-var-gated skip
  # doesn't fire. Kept as a package, not a check (matches bats-hyphence/
  # validate-grammar's existing convention — langlang is a less-vetted
  # external input than igloo/nixpkgs-master). Only built when langlang is
  # supplied; assert()s a clear message if grammarPeg is missing alongside it.
  grammar-vectors-test =
    assert (langlang == null) || (grammarPeg != null);
    pkgs.buildGoApplication {
      pname = "hyphence-grammar-vectors-test";
      inherit version goFlakeInputs;
      src = ./.;
      pwd = ./.;
      modules = ./gomod2nix.toml;
      go = pkgs-master.go_1_26;
      GOTOOLCHAIN = "local";
      subPackages = [ "hyphence" ];

      nativeBuildInputs = pkgs-master.lib.optionals (langlang != null) [
        langlang.packages.${system}.default
      ];

      buildPhase = ''
        runHook preBuild
        go build ./...
        runHook postBuild
      '';

      doCheck = true;
      checkPhase = ''
        runHook preCheck
        export LANGLANG_BIN=langlang
        export HYPHENCE_GRAMMAR_PEG=${grammarPeg}
        go test -tags test -run TestGrammarVectors -v ./...
        runHook postCheck
      '';

      installPhase = ''
        runHook preInstall
        mkdir -p "$out"
        runHook postInstall
      '';
    };

  # The hyphence CLI binary (cmd/hyphence). igloo's buildGoApplication injects
  # the version arg as `-X main.version`, so `var version` in main.go carries the
  # version.env HYPHENCE_VERSION at link time. When man7Src/man1Src is set,
  # postInstall renders docs/man.{7,1}/*.md to roff man pages via pandoc (each
  # man page's YAML frontmatter supplies the title), so `man hyphence` (7,
  # the format) and `man 1 hyphence` (the CLI) both work after install.
  hyphence = pkgs.buildGoApplication {
    pname = "hyphence";
    inherit version goFlakeInputs;
    src = ./.;
    pwd = ./.;
    modules = ./gomod2nix.toml;
    subPackages = [ "cmd/hyphence" ];
    go = pkgs-master.go_1_26;
    GOTOOLCHAIN = "local";

    nativeBuildInputs = pkgs-master.lib.optionals (man7Src != null || man1Src != null) [
      pkgs-master.pandoc
    ];

    postInstall = ''
      ${pkgs-master.lib.optionalString (man7Src != null) ''
        mkdir -p $out/share/man/man7
        for f in ${man7Src}/*.md; do
          name="$(basename "$f" .md)"
          pandoc -s -t man "$f" -o "$out/share/man/man7/$name.7"
        done
      ''}
      ${pkgs-master.lib.optionalString (man1Src != null) ''
        mkdir -p $out/share/man/man1
        for f in ${man1Src}/*.md; do
          name="$(basename "$f" .md)"
          pandoc -s -t man "$f" -o "$out/share/man/man1/$name.1"
        done
      ''}
    '';

    meta.mainProgram = "hyphence";
  };
in
{
  packages = {
    inherit hyphence;
    default = hyphence;
  }
  # grammar-vectors-test is only defined meaningfully when langlang is
  # supplied — a bare `import ./go/default.nix` (langlang defaults null)
  # never forces it, so the unconditional `${grammarPeg}` interpolation
  # in its checkPhase is never evaluated for non-flake callers.
  // pkgs-master.lib.optionalAttrs (langlang != null) { inherit grammar-vectors-test; };

  checks = {
    inherit go-test;
  };

  devShells.default = pkgs-master.mkShell {
    packages = [
      (pkgs.mkGoEnv {
        pwd = ./.;
        inherit goFlakeInputs;
      })
      # gomod2nix CLI for `just build-gomod2nix` / `just update-go`. Sourced
      # from igloo (matching the gomod2nix the conformist drift linter runs)
      # so the regenerated gomod2nix.toml byte-matches what the linter expects.
      pkgs.gomod2nix
    ]
    ++ pkgs-master.lib.optionals (doppelgang != null) [
      doppelgang.packages.${system}.default
    ]
    # The BARE conformist binary plus the formatter/linter tools the generated
    # config drives that aren't in the pkgs-master block below.
    ++ pkgs-master.lib.optionals (conformist != null) [
      conformist.packages.${system}.default
      pkgs.nixfmt
      pkgs-master.shellcheck
    ]
    # The per-commit hook wrapper, on PATH as `conformist-pre-commit` for the
    # sweatfile [hooks].pre-commit command.
    ++ pkgs-master.lib.optionals (conformistPreCommit != null) [
      conformistPreCommit
    ]
    # Its merge-repair sibling, on PATH as `conformist-repair` for the
    # sweatfile [hooks].repair command (see the conformistRepair param doc).
    ++ pkgs-master.lib.optionals (conformistRepair != null) [
      conformistRepair
    ]
    ++ (with pkgs-master; [
      gofumpt
      gopls
      gotools
      just
      shfmt
    ])
    # Rust toolchain for the rust/ sibling crate: `just test-rust` (cargo test)
    # and ad-hoc cargo/rustfmt. Sourced from igloo (pkgs) to match the
    # rustPlatform that builds checks.rust-test.
    ++ (with pkgs; [
      cargo
      rustc
      rustfmt
    ]);

    GOTOOLCHAIN = "local";
  };
}
