schema = 3

[mod]
  [mod.'code.linenisgreat.com/purse-first/libs/dewey']
    version = 'v0.5.0'
    hash = 'sha256-WaAb5xVdkek2jtlcD8y+99VuZyAoCVzezyIrs5X9Mbg='
    goVersion = '1.26'

  [mod.'github.com/google/go-cmp']
    version = 'v0.7.0'
    hash = 'sha256-JbxZFBFGCh/Rj5XZ1vG94V2x7c18L8XKB0N9ZD5F2rM='
    goVersion = '1.21'

  [mod.'golang.org/x/sys']
    version = 'v0.43.0'
    hash = 'sha256-aDQXqSTZES2l/132PBxhZN4ywldpPyfm7LByYCHzzwM='
    goVersion = '1.25.0'

  [mod.'golang.org/x/term']
    version = 'v0.42.0'
    hash = 'sha256-FCiDvAfq7dgBGQuiDYDFJbj/JPawhrmPF2qdUEftQ1c='
    goVersion = '1.25.0'

  [mod.'golang.org/x/text']
    version = 'v0.36.0'
    hash = 'sha256-/0t9C6Mc8kYjxweFB0us2lGKo8GovHhBiq5nlMOppC0='
    goVersion = '1.25.0'

  [mod.'golang.org/x/xerrors']
    version = 'v0.0.0-20240903120638-7835f813f4da'
    hash = 'sha256-bE7CcrnAvryNvM26ieJGXqbAtuLwHaGcmtVMsVnksqo='
    goVersion = '1.18'

  [mod.'mvdan.cc/sh/v3']
    version = 'v3.13.1'
    hash = 'sha256-FM+2xpGELZLm4Gc09OE5Z3JeNLPMvzeb1wRcdAIeKy4='
    goVersion = '1.25.0'
